x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app:cached # cached: The container may cache mounted source files for better performance.
    - ./storage:/app/storage
  environment:
    RAILS_ENV: development
    RAILS_LOG_TO_STDOUT: 'true'
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST: db
    REDIS_URL: redis://redis:6379/0
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started

services:
  web:
    <<: *app
    ports:
      - "3000:3000"

  sidekiq:
    <<: *app
    command: bundle exec sidekiq

  db:
    image: postgres:16-bookworm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rv_marketplace_development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-bookworm

volumes:
  db_data: {}
