services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached # cached:The container may cache the mounted (all source) files for better performance.
      - ./storage:/app/storage
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bookworm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rv_marketplace_development
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
