services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached # cached:The container may cache the mounted (all source) files for better performance.
      - ./storage:/app/storage
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'

# Optional: add a db service if you switch to Postgres in future
# volumes:
#   db_data: {}
